import Link from "next/link";
import { Footer, PilotShell } from "@/components/pilot-shell";
import { demoParticipant, stations } from "@/lib/demo-data";
import { featureFlags } from "@/lib/theme";
import { QrCode } from "@/components/qr-code";

export default async function ParticipantPage({ params }: { params: Promise<{ code: string }> }) {
  const { code } = await params; const participant = { ...demoParticipant, code: code.toUpperCase() };
  return <PilotShell><main className="page"><p className="eyebrow">Persoonlijke pagina</p><h1>Hoi {participant.firstName}</h1><div className="status-row"><strong>{participant.variant} · Strippenkaart</strong><span className="status">{participant.status}</span></div><p className="muted">Geldig tot 27 november. Je fysieke kaart telt altijd.</p><section><h2>Vandaag</h2><p>Heb je vandaag koffie gehaald bij Kiosk?</p><div className="choice-row"><button>Ja</button><button className="secondary">Nee</button></div><p className="hint">Eén keer per dag; een nieuwe dag start om 04:00.</p></section><section><h2>Koffie gehaald</h2><p>Nog ongeveer <strong>{participant.maxRedemptions - participant.redemptions} van {participant.maxRedemptions}</strong> strippen. Indicatie, je kaart telt.</p><label>Station<select defaultValue=""><option value="" disabled>Kies een station</option>{stations.map((station) => <option key={station.code}>{station.name}</option>)}</select></label><button>Registreer koffie</button></section><section><h2>Deze week</h2><p>De wekelijkse vragenlijst duurt ongeveer twee minuten.</p><Link className="button-link" href={`/w/${participant.code}/1`}>Open vragenlijst</Link></section>{featureFlags.ordering && <section><h2>Voorbestellen</h2><p>Je hebt nog geen open bestelling.</p><Link className="button-link" href={`/k/${participant.code}/bestel`}>Koffie voorbestellen</Link></section>}<section><h2>Jouw kaart</h2><p className="participant-code">{participant.code}</p><QrCode value={`/k/${participant.code}`} /><p className="hint">Toon altijd je fysieke kaart bij de kassa.</p>{featureFlags.digitalStampCard && <Link href={`/k/${participant.code}/stempels`}>Open digitale stempelkaart</Link>}</section></main><Footer /></PilotShell>;
}
