export const content = {
  nl: {
    navigation: {
      privacy: "Privacyverklaring",
      footer: "Pilot van Limpid & Co in opdracht van NS Retail",
    },
    home: {
      eyebrow: "NS Retail Preorder Pilot",
      title: "Koffie ophalen, zonder wachten.",
      lead: "Een besloten pilot voor deelnemers en kioskteams in Amersfoort en Gouda.",
    },
    participant: {
      eyebrow: "Persoonlijke pagina",
      greeting: "Hoi",
      card: "Strippenkaart",
      validUntil: "Geldig tot 27 november. Je fysieke kaart telt altijd.",
      today: "Vandaag",
      question: "Heb je vandaag koffie gehaald bij Kiosk?",
      yes: "Ja",
      no: "Nee",
      reset: "Eén keer per dag; een nieuwe dag start om 04:00.",
      redemption: "Koffie gehaald",
      remainingBefore: "Nog ongeveer",
      remainingBetween: "van",
      remainingAfter: "strippen. Indicatie, je kaart telt.",
      station: "Station",
      chooseStation: "Kies een station",
      register: "Registreer koffie",
      addOn: "Wat heb je erbij gehaald?",
      addOnOptions: {
        nothing: "Niets",
        food: "Iets te eten",
        other: "Iets anders",
      },
      registrationUnavailable: "Je registratie kon niet worden opgeslagen. Probeer het later opnieuw.",
      week: "Deze week",
      weekIntro: "De wekelijkse vragenlijst duurt ongeveer twee minuten.",
      weekLink: "Open vragenlijst",
      preorder: "Voorbestellen",
      noOpenOrder: "Je hebt nog geen open bestelling.",
      preorderLink: "Koffie voorbestellen",
      cardTitle: "Jouw kaart",
      cardHint: "Toon altijd je fysieke kaart bij de kassa.",
      stampLink: "Open digitale stempelkaart",
      qrAlt: "QR-code naar je persoonlijke pilotpagina",
      statuses: {
        active: "actief",
        paused: "gepauzeerd",
        blocked: "geblokkeerd",
      },
    },
    order: {
      eyebrow: "Voorbestellen",
      title: "Bestel je koffie",
      station: "1. Station",
      drink: "2. Drank",
      slot: "3. Tijdslot",
      slotsUnavailable:
        "Slots worden zichtbaar zodra technisch beheer voorbestellen activeert.",
      back: "Terug naar jouw pagina",
      open: "Nu open",
      closed: "Tijdelijk gesloten",
      chooseDrink: "Kies een drank",
      chooseSlot: "Kies een tijdslot",
      chooseProduct: "Kies eerst een drank",
      option: "Optie",
      noOption: "Geen voorkeur",
      submit: "Bestellen",
      unavailable: "Deze bestelling kon niet worden opgeslagen. Kies opnieuw een beschikbaar slot.",
      confirmation: "Je bestelling",
      status: "Status",
      cancel: "Bestelling annuleren",
      cancelUnavailable: "Annuleren is niet meer mogelijk binnen tien minuten voor het tijdslot.",
      noProducts: "Er zijn voor dit station nog geen producten beschikbaar.",
      noSlots: "Er zijn nu geen beschikbare tijdsloten.",
      slotAvailable: "Vrij",
      slotFull: "Vol",
      statuses: { received: "Ontvangen", collected: "Afgehaald", not_collected: "Niet afgehaald", cancelled: "Geannuleerd", unknown: "Onbekend" },
    },
    store: {
      connected: "Verbonden · zojuist bijgewerkt",
      polling: "Polling actief · elke 10 seconden bijgewerkt",
      disabled: "Het winkelscherm is tijdelijk uitgeschakeld door technisch beheer.",
      empty: "Geen open bestellingen",
      emptyHint: "Nieuwe bestellingen verschijnen hier vanzelf.",
      pause: "Even geen bestellingen",
      log: "Dagelijks logboek openen",
      collected: "Klaar en afgehaald",
      noShow: "Klaar, niet afgehaald",
      orderNumber: "Bestelnummer",
      due: "Tijdslot",
      resume: "Weer openen",
      pauseUntil: "Pauze actief tot",
      voucher: "Beloningsbon inwisselen",
      voucherCode: "Boncode",
      voucherSubmit: "Bon inwisselen",
    },
    signup: {
      eyebrow: "Wachtlijst",
      title: "Wil je voorbestellen proberen?",
      intro: "Laat je gegevens achter en ontvang een eenmalige beloningsbon.",
      email: "E-mailadres",
      station: "Station",
      frequency: "Hoe vaak reis je?",
      when: "Wanneer had je willen voorbestellen?",
      price: "Wat heb je ervoor over?",
      priceOther: "Ander bedrag",
      formats: "Welke vorm spreekt je aan?",
      trial: "Wil je meedoen aan een proef?",
      consent: "Ik ga akkoord met de privacyverklaring.",
      submit: "Aanmelden",
      frequencies: ["Dagelijks", "Wekelijks", "Soms"],
      priceOptions: ["€ 0", "€ 0,50", "€ 1", "Anders"],
      formatOptions: ["Stempel", "Strippenkaart", "Korting", "Tegoed om te delen", "Abonnement", "Dalkorting"],
      yes: "Ja",
      no: "Nee",
      messages: { duplicate: "Dit e-mailadres is al aangemeld. Er is geen tweede bon gemaakt.", invalid: "Controleer je gegevens en probeer het opnieuw.", rate_limited: "Probeer het later opnieuw." },
    },
    voucher: { eyebrow: "Beloningsbon", title: "Je beloningsbon", intro: "Bewaar dit scherm en laat het zien aan de kassa.", cardTitle: "Eenmalige bon", station: "Station", validUntil: "Geldig tot", noExpiry: "Geen einddatum", instructions: "Laat dit scherm zien aan de kassa." },
    admin: {
      eyebrow: "Beheer",
      title: "Pilotbeheer",
      intro:
        "Beheeraccounts gebruiken Supabase Auth met tweestapsverificatie. Deze lokale startweergave toont de in te richten onderdelen.",
      ready: "Inrichten zodra beheerder is aangemeld.",
      stations: "Startstations",
      sections: [
        "Deelnemers",
        "Bestellingen",
        "Wachtlijst & bonnen",
        "Stations & producten",
        "Codes & QR-velden",
        "Exports & tokens",
      ],
    },
    adminSessions: {
      title: "iPad-sessies",
      active: "Actieve sessies",
      lastSeen: "Laatst actief",
      none: "Geen actieve iPad-sessies.",
      confirmation: "Typ de stationcode om alle iPad-sessies in te trekken.",
      submit: "Trek alle iPad-sessies in",
      pinTitle: "Winkel-PIN roteren",
      pin: "Nieuwe viercijferige PIN",
      pinConfirmation: "Herhaal nieuwe PIN",
      pinSubmit: "Roteer PIN en trek sessies in",
    },
    adminManagement: {
      participants: "Deelnemers",
      products: "Producten",
      exports: "Exports",
      create: "Aanmaken",
      save: "Opslaan",
      rotateCode: "Code roteren",
      revoke: "Intrekken",
      firstName: "Voornaam",
      cohort: "Meetgroep",
      variant: "Variant",
      station: "Station",
      origin: "Herkomst",
      channel: "Kanaal",
      status: "Status",
      canPreorder: "Mag voorbestellen",
      blockedReason: "Reden blokkade",
      notes: "Opmerkingen",
      code: "Actieve code",
      name: "Naam",
      options: "Opties, gescheiden door komma's",
      position: "Volgorde",
      active: "Actief",
      dataset: "Dataset",
      noParticipants: "Er zijn nog geen deelnemers ingevoerd.",
      noProducts: "Er zijn nog geen producten ingevoerd.",
      noTokens: "Er zijn nog geen exporttokens aangemaakt.",
      exportUrl: "Eenmalig zichtbare export-URL",
      statuses: { active: "Actief", paused: "Gepauzeerd", blocked: "Geblokkeerd" },
      privacy: "Persoonsgegevens anonimiseren",
      retentionUntil: "Bewaartermijn tot en met",
      anonymizeWarning: "Deze actie is onomkeerbaar: voornamen, e-mails, vrije tekst en actieve toegangscodes worden gewist of ingetrokken.",
      anonymizeConfirmation: "Typ ANONIMISEREN om door te gaan",
      anonymize: "Anonimiseer persoonsgegevens",
    },
    features: {
      title: "Pilotonderdelen",
      enabled: "Aan",
      disabled: "Uit",
      save: "Opslaan",
      ordering: "Voorbestellen",
      store_screen: "Winkelscherm",
      digital_stamps: "Digitale stempelkaart",
      card_photos: "Kaartfoto’s",
      email_delivery: "E-mailverzending",
    },
    adminLogin: {
      eyebrow: "Beheer",
      title: "Inloggen",
      email: "E-mailadres",
      password: "Wachtwoord",
      submit: "Inloggen",
    },
    adminMfa: {
      eyebrow: "Beheer",
      title: "Tweestapsverificatie",
      code: "Code uit authenticator-app",
      submit: "Verifiëren",
    },
    storeLogin: {
      eyebrow: "Winkel",
      pin: "Viercijferige PIN",
      submit: "Open winkelscherm",
    },
    privacy: {
      eyebrow: "Privacy",
      title: "Privacyverklaring pilot",
      body: "Deze pilot verwerkt een deelnemerscode en voornaam. De wachtlijst verwerkt daarnaast een e-mailadres voor de gevraagde beloningsbon. Er zijn geen betalingen, advertenties of externe analytics.",
      retention:
        "Gegevens staan in de EU en worden na de ingestelde bewaartermijn geanonimiseerd.",
    },
    catalog: { noStations: "Er zijn momenteel geen stations beschikbaar.", noProducts: "Er zijn momenteel geen producten beschikbaar." },
  },
  en: {} as Record<string, never>,
} as const;

export const ui = content.nl;
